### ISSUE TITLE
Crash in lightspark::RenderThread::allocateNewGLTexture() on Fedora 39

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#1105]
Since #1104 was fixed by 24b792968bae22241fff20d42f1f481c7e41d282, I'm now getting a crash with a different backtrace [bt.log](https://github.com/lightspark/lightspark/files/12640141/bt.log)

With the following swf: [qwop.zip](https://github.com/lightspark/lightspark/files/12639825/qwop.zip)

The same crash also happened with other SWFs I tried.

**Comment by dbluelle** [comment]
Hmm, I couldn't reproduce that. 
There seems to be something wrong with the OpenGL calls.
I get that sometimes when I had crashes of lightspark and the OpenGL driver gets into an unstable state.
In that case restarting the computer might help.

**Comment by eiglow** [comment]
I tried restarting my computer and running it again, same result.

I initially suspected Mesa might be at fault, because my desktop is running 23.2.0-rc3, so I tried my laptop with 23.1.7, and same result.

I then tried an X11 session, and it ran the file successfully.

**Comment by dbluelle** [comment]
Just to be sure, you have set the SDL_VIDEODRIVER=wayland environment variable when running from wayland?

**Comment by eiglow** [comment]
Yes. If I don't set it, I get #958.

**Comment by dbluelle** [comment]
I've tested lightspark on wayland on Arch linux and it runs without problems, so I'm not sure what causes your crashes.
The log indicates that the first errors occur during setup of the OpenGL variables in RenderThread::commonGLInit.
Maybe the recent switch to OpenGL 3 triggers something...
Just to be sure please rebuild lightspark from an empty build directory, so that no artifacts from earlier builds remain.

**Comment by dbluelle** [comment]
I've fixed another OpenGL issue that _may_ also help with your issue (but I doubt it...).

**Comment by eiglow** [comment]
I'm not sure if the recent commits helped, or if the fresh build directory helped, but either way, it seems to be fixed now.
