### ISSUE TITLE
`uint` not standard and not available in MinGW

### ISSUE THREAD

**Issue by wyatt8740** [lightspark/lightspark#270]
I'm trying to build LightSpark from master for windows, as the official release is very out of date. I've hit a few bugs; the one I'm facing now is that in several spots the code uses the shortcut `uint` for `unsigned int`, but does not actually make a `#define` anywhere. This causes the code to fail to compile in MinGW as set up with MXE. It's not done building as of this writing, but adding `#define uint unsigned int` did the job in the files where `uint` was used. The proper solution would be to actually change all instances of `uint` to `unsigned int`.

(the other of note is that MXE cannot find GLUT to build caca unless you copy the `freeglut.pc` file to `glut.pc`. This would just be a documentation issue since it's not mentioned in `README.win32`).

**Comment by dbluelle** [comment]
I've changed all uints to unsigned ints.
The freeglut issue seems to be fixed in mxe ( see https://github.com/mxe/mxe/commit/7d381a4edfac61d6e0b3dd5ce11648620ff25c60 )
I've also added some fixes for MinGW compilation.
However I still get some linking errors I wasn't able to resolve.
(I won't investigate further for now, as I don't even have a Windows installation to test... )

**Comment by wyatt8740** [comment]
Alright, thanks for taking a look. I still can't compile it either, but I'm getting closer. I was going to test it in wine and then copy it over to my windows XP Pentium III laptop :\
