### ISSUE TITLE
Can (or is already) Lightspark use Adobe's ActionScript implementation?

### ISSUE THREAD

**Issue by ethus3h** [lightspark/lightspark#278]
There is apparently a libre ActionScript implementation from Adobe: https://github.com/adobe/avmplus

Can this be used to supplement Lightspark's ActionScript support, or is it already?

**Comment by dbluelle** [comment]
That looks to me as if it's just a clone of the tamarin repository http://hg.mozilla.org/tamarin-redux .
AFAIK this is a tool for _producing_ swf files, not for playing them.
However, we're already using tamarin for testing our implementation (see tests/make-tamarin).
Maybe we should switch to the adobe repository for testing, as there seems to be no more activity on tamarin...

**Comment by ethus3h** [comment]
Aww, oh well :( Thanks!

**Comment by ethus3h** [comment]
Wait, are you sure? Like, it looks like [this](https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/shell/SystemClass.cpp#L309) implements [this which is missing from Lightspark](https://github.com/lightspark/lightspark/blob/811f8ec7b8140fd804e4b839fb1f7c6176423c73/src/scripting/avmplus/avmplus.cpp#L127).

**Comment by ethus3h** [comment]
It's in Tamarin, though, too... https://hg.mozilla.org/tamarin-redux/file/5571cf86fc68/shell/SystemClass.cpp#l266

**Comment by dbluelle** [comment]
IMHO that's only the implementation of  the avmplus package, which does not belong to the official flash platform, see http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/ .
Most of the methods of the avmplus package are also available in the flash.system.System class.
We have only added a stub implementation of avmplus, so that the tamarin tests do not crash.
I've not seen any real world swf file that uses the avmplus package, so it's not high priority to implement it.
However, taking the code from tamarin would mean that we also have to use more of tamarin, like e.g. the garbage collector "MMgc".
This looks like a lot of additional work...

**Comment by ethus3h** [comment]
Ah, oh well. Thanks anyway :)
