### ISSUE TITLE
Unable to build on Ubuntu 16.10 Latest code since commit #308241e

### ISSUE THREAD

**Issue by sudo-apt-get-install** [lightspark/lightspark#281]
I have all of the dependencies installed obviously since I ran apt list --installed | grep "the various dependencies" and found them all

The error in terminal
pastebin.com/0qz8zDVu

The error in CMakeError.log
pastebin.com/4EqnAtrd

**Comment by ethus3h** [comment]
Do you really have liblzma (and its associated development package, since IIRC Debian/Ubuntu split them) installed?

**Comment by ethus3h** [comment]
308241e builds just fine for me, for what it's worth.

**Comment by sudo-apt-get-install** [comment]
Oh thank you for telling me to install the dev packages because I had all of the packages but not the dev packages after a couple hours of apt list | grep "" I found them all and installed them then cmake worked.

But now make gives me an error 

pastebin.com/UEa8PxXn

**Comment by dbluelle** [comment]
cmake seems to have not properly detected ffmpeg.
Please clear your build directory and run cmake again.

**Comment by sudo-apt-get-install** [comment]
But CMake ran without a hitch after I installed the dev packages of every single thing that had already been installed, including FFmpeg-dev. So why is Make not working?

**Comment by dbluelle** [comment]
That's because cmake caches a lot of stuff in the build directory and it may still have some wrong values cached.
So I think it's better to start with a clean build directory whenever something changes in the dependencies, especially when make hasn't worked previously.

Please try it with a clean build directory and if it still doesn't work, post the output of cmake here.

**Comment by sudo-apt-get-install** [comment]
I tried it with a fresh download and 
https://pastebin.com/tYLiiEKp

**Comment by dbluelle** [comment]
That is the wrong log.
I need the output of the cmake step, not make

**Comment by sudo-apt-get-install** [comment]
I don't understand why you need the CMake log because Make is the thing that errors. But here you go anyway 

So I redownloaded the source because you had committed a change, so it's fresh source again.
Then I ran CMake and here is the [terminal](https://pastebin.com/7B0bC9Ev), [CMakeOutputLog](https://pastebin.com/RGK89zxq), and the [CMakeErrorLog](https://pastebin.com/qWnarWvV)

**Comment by sudo-apt-get-install** [comment]
Closed? UH I THINK NOT 

I got a whole new world of errors

[Make Terminal](https://pastebin.com/ryjBtFZC)
[CMake Terminal](https://pastebin.com/GXTtyrhk)
[CMakeOutput](https://pastebin.com/TvX95KG1)
[CMakeError](https://pastebin.com/MssVUPRe)

**Comment by ethus3h** [comment]
Latest commit https://github.com/lightspark/lightspark/commit/6dc2efcf5a71beaa59a04b6bf52acada7aef610f builds fine for me.

**Comment by sudo-apt-get-install** [comment]
TELL ME HOW NOTHING IS WORKING

TELL ME YOUR SEEECREETS

**Comment by ethus3h** [comment]
I'm using [this ebuild (Portage build script)](https://github.com/ethus3h/wreathe-overlay/blob/master/www-plugins/lightspark/lightspark-9999.ebuild). I don't know what you're doing differently from that, but I'd check:

1. Are you using a completely clean, up-to-date copy of the source?
2. The plethora of ffmpeg errors makes me think you might be building against an outdated ffmpeg?
3. If the above fail, check again that you have all the needed dependencies (check against the documentation and against the ebuild I linked above), that your cmake arguments are correct when building, and that you're building it correctly.

Other than that, I can't really help since I don't know enough about Ubuntu. (I used it a few years ago and found it hard to track down the right dependency packages for compiling things; granted I probably just didn't understand how the package manager works. I vaguely remember a command like "apt-get build-deps lightspark" or something that would try to get them automatically though, but I could be misremembering, and that doesn't do any good for packages that aren't already available as binaries I think. My 2¢ is that Portage is easier to use than apt for working with packages built from source; if you remove the dependencies from that ebuild and make sure you have any needed eclasses, you might even be able to use that ebuild with Portage to build lightspark, but if this is a dependency error it wouldn't be able to fix it since your whole system isn't in Portage.)

**Comment by sudo-apt-get-install** [comment]
Completely clean with no additions other than the obj folder
I just installed the FFmpeg-dev package from apt 10 days ago.
Everything is installed

**Comment by dbluelle** [comment]
Sorry, I forgot one file in the last commit.
Should be fixed now.

**Comment by sudo-apt-get-install** [comment]
Thank you, it is fixed now

**Comment by sudo-apt-get-install** [comment]
Alright nevermind, so the compilation is fixed but Firefox isn't detecting Lightspark

**Comment by dbluelle** [comment]
Check if the firefox plugin is installed into one of the directories where firefox looks for plugins.
By default everything is installed in /usr/local, on Archlinux I set CMAKE_INSTALL_PREFIX to /usr to ensure the binaries are installed in the correct directories.

**Comment by sudo-apt-get-install** [comment]
Well I installed Adobe Flash and it put it in a completely different directory so I put lightspark in that same directory and then it said it was corrupt

**Comment by dbluelle** [comment]
What's the output of the make install step?
Maybe the plugin doesn't find the main library because of the different install path.
I think it would be better to adjust the install directory and _not_ copy the files manually.
