### ISSUE TITLE
Crunchyroll Manga support

### ISSUE THREAD

**Issue by sandy-8925** [lightspark/lightspark#311]
I was able to download Crunchyroll's manga viewer SWF file, and run it locally using lightspark, and get it to work. However, it fails to work in the browser for both Chrome and Firefox. Apparently the plugin crashes - could you guys help me figure out how to debug this? How would I find out the stacktrace and the cause of the crash?

**Comment by dbluelle** [comment]
Debugging used to work on firefox following the directions on https://github.com/lightspark/lightspark/wiki/Debugging-tools, but (I think) since the plugin is running in the separate process, it doesn't work anymore...
It should be possible to somehow connect to the plugin process using gdb, but I don't know how that works. 
However, if you run a debug version of the plugin, you can get a more detailed log output by pressing Ctrl+L. 
Feel free to post the output here.
