### ISSUE TITLE
some comments on screenshots

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#426]
@dbluelle,

many thanks for having implemented screenshots in LS. I have some comments:

1. Wouldn’t _Ctrl+S_ be a more intuitive shortcut for screenshots?

1. How about saving image files at home (`~/`) instead of `/tmp`?

1. Wouldn’t it be better to use PNG instead of uncompressed bitmaps? Otherwise, resulting files are huge.

And I have an issue with screenshots at fullscreen size (but this requires a proper and separate report).

Many thanks for your help.

**Comment by dbluelle** [comment]
1) I've not found a "standard" shortcut for creating screenshots, so I chose Ctrl+O because it's the same shortcut that gnash uses.
I'm open to suggestions (IMHO Ctrl+S is also not a good choice, as both Ctrl+O/S are commonly used in applications for opening/saving files).
Does anyone know if the adobe player/projector has screenshot creation?
2) It was easiest to just write to a temporary file and let the OS handle the path where it is put.
This way, we are guarranteed to have a writable location on all operating systems.
3) Well, bmp format is the easiest to write, is guarranteed to have no compression artifacts and doesn't need any external library, so I chose that.
On my monitor a fullscreen screenshot (1900x1200) takes ~7 MB, I think that is acceptable.
You can always convert it into a png by using some tool like ImageMagick or the graphic tools of Gnome/KDE etc.

**Comment by ousia** [comment]
@dbluelle,

1. That was copied from https://mpv.io/ (they use Ctrl+S). I know that Ctrl+S is used to save contents. But unless you want to enable the saving of a copy of the SWF file, saving a screenshot image with Ctrl+S is fine (I’d say).

1. It took it from https://mpv.io/. But _mpv_ saves the image to the current directory (I thought images were saved to the home directory).

1. Bitmap is fine. I was also inspired by https://mpv.io/. But I forgot they saved images as JPG (instead PNG). It is better to compress bitmaps with the method that suits best for their images.

Just in case it might help.

**Comment by dbluelle** [comment]
1. I've switched the shortcut to Ctrl+S, that's at least better than Ctrl+O.
2. IMHO Using the current directory for screenshot saving is a bad idea, as you can never be sure that directory is writable.
I'm closing this now, but anyone feel free to open a new issue if you have a better idea for any of these points
