### ISSUE TITLE
check before saving screenshot in current directory

### ISSUE THREAD

**Issue by ousia** [lightspark/lightspark#431]
@dbluelle,

I think a better approach to save screenshots in the current directory is simple.

Check whether the directory allows writing new files (https://stackoverflow.com/a/3799146) first.

If the directory allows new files, write the image there. If not, save the image to the temporary directory.

Many thanks for your help.

**Comment by eiglow** [comment]
That would save the screenshots in the same directory as the lightspark binary, which, if the user installed lightspark using `make install`, will be somewhere like `/usr/local/bin`, and somewhere else entirely if the user installed using a package manager.

Perhaps the screenshots can be saved somewhere in the user's home directory, like `~/Pictures/lightspark`?

**Comment by ousia** [comment]
@eiglow,

I’m afraid I meant something different with “the current directory from where is invoked”, but I’m afraid I cannot provide a more accurate description.

Check it with the `mpv` player.

**Comment by dbluelle** [comment]
I think saving in the folder where the swf file is located is a bad idea, because it is not guarranteed that that folder is writable (think e.g. starting an swf from a dvd).
And where should that folder be when generating a screenshot from the plugin inside the browser?
Anyway what is the problem with the temp folder?
IMHO it's the best solution as it's always writable and you always know where to look for your screenshot.

**Comment by ousia** [comment]
@dbluelle,

many thanks for your reply.

I thought the proposal made sense, but it seems that (at least) I’m not able to explain it.

Closing the issue myself.
