### ISSUE TITLE
Debug build failing due to invalid assert

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#463]
#460 seems to have introduced an invalid assert, on line 7477 of `abc_interpreter.cpp`.
```
/lightspark/src/scripting/abc_interpreter.cpp:7445:33: error: request for member ‘len’ in ‘* defaultlocaltypes’, which is of pointer type ‘lightspark::Class_base*’ (maybe you meant to use ‘->’ ?)
```
Using `->` as suggested just caused the same error. I tried changing the line to
```
assert(i < (*defaultlocaltypes)->len && "array out of bounds!");
```
but that gives a different error now:
```
/lightspark/src/scripting/abc_interpreter.cpp:7445:36: error: ‘class lightspark::Class_base’ has no member named ‘len’
```
@jhwgh1968 Could this assert be re-worked? It seems like the only good way to get the length of an array in C++ is with `std::size()`, but that requires compiling with `-std=c++17`, and possibly including the iterator header if I'm reading the docs right.

**Comment by jhwgh1968** [comment]
Sorry to break your build, @eiglow! I didn't think it was a problem, because it worked for me, and CI tests both clang and gcc toolchains. What compiler are you using?

Either way, I would not strongly object to you opening a PR which just removes that line. The assert was just to clear up a `scan-build` analysis flag, making clear that the given condition could not be violated. I never actually got it to trigger on my own test files, and it was not the source of the actual bug I fixed.

**Comment by eiglow** [comment]
I'm using gcc 9.2.1. To be clear, the normal release build is fine, it's only the debug builds that fail, because that's when the assert is compiled in. I'm not sure that the CI tests debug builds.

**Comment by jhwgh1968** [comment]
You are right, they don't. Based on this mistake of mine, perhaps they should!

**Comment by eiglow** [comment]
@dbluelle Do you know if there is a way to check the length of `defaultlocaltypes` in this context? I'd rather not just remove asserts that could be useful.

**Comment by dbluelle** [comment]
AFAIK there is no method to detect the size of a dynamically allocated c array, so I don't think we can do a proper "assert" here.

**Comment by dbluelle** [comment]
I've removed the line and added a comment, if someone knows a way to check this
