### ISSUE TITLE
Hero Fighter - takes a very long time to get to main menu

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#592]
[SWF](https://drive.google.com/file/d/1sP0U7bz2XWSgZrYW1Qrubd9ooRFXszM-/view?usp=sharing)
Tested on current master (edf083bf4c90228cb57347915b5ca4cf9937939f)

When running the game with Lightspark, for me it took about 35 seconds to reach the main menu, while Adobe flash took about 2 seconds. In addition, Lightspark uses a large amount of RAM, I observed >2GB, while Adobe uses about ~280MB once the main menu is reached.

[Terminal output](https://github.com/lightspark/lightspark/files/5732582/hf.log)
[Terminal output with `-l 4`](https://github.com/lightspark/lightspark/files/5732587/hf-l4.zip)

**Comment by huwdp** [comment]
I recommend opening Lightspark with Valgrind and seeing what the issue is.

Callgrind: '''valgrind --tool=callgrind [callgrind options] your-program [program options'''

For memory leaks, you can check this page here (https://stackoverflow.com/a/44989219). 

I'll have a quick check tomorrow and see if anything is out of the ordinary.

If you have any issues with Segfault, you can use a tool like RR (https://rr-project.org/) and record the program execution and replay to get error. I haven't used this yet

**Comment by huwdp** [comment]
![image](https://user-images.githubusercontent.com/364976/103161965-c5ff7900-47e1-11eb-9713-942605bda36c.png)

[callgrind.zip](https://github.com/lightspark/lightspark/files/5743968/callgrind.zip)

A lot of work is done in those three functions in screenshot. Latest build of Lightspark hits an assertion.

**Comment by dbluelle** [comment]
all callgrind outputs will look similar at the top if the swf file uses actionscript3, as SyntheticFunction::call, ABCVm::executeFunction and asAtomHandler::callFunction are more or less called every time some actionscript code is executed. So you have to look at the methods further down the list to find potential candidates for optimization.

**Comment by eiglow** [comment]
As of latest master (63771d2dd3efa7b32f80f9c1263f0a8647a4b2ea), I don't get this anymore. Lightspark only takes about 3-4 seconds to reach the main menu. RAM usage is still very high (2.2 GiB), but I guess that's unrelated to this issue.
