### ISSUE TITLE
LightSpark is fake

### ISSUE THREAD

**Issue by GGor1** [lightspark/lightspark#658]
LightSpark is falsely marketing it self as an alternative to Adobe Flash. LightSpark does NOT function at all on Windows. LightSpark does NOT have a plugin for Chrome, Firefox or Edge. LightSpark is not buggy since it has to function first before any bugs can be found.

**Comment by huwdp** [comment]
Lightspark is not fake lol. It is true that Lightspark won't run on the latest version of Firefox and Chrome but that's due to their decision to remove external plugins in their software.

Lightspark can be run in other web browsers such as Pale Male, Waterfox, etc but you'll have to copy the dlls to the web browser plugin folder(s). Maybe Lightspark will be able to run in the web browser via wasm but only time will tell.

You can download and run swf files within Lightspark via command line if you wanted to. This is my preferred option.

Lightspark is currently in alpha so you'll find bugs while running swf files. Adobe hasn't made it easy as they have not open sourced their AS3 API, etc so the task of reverse engineering their API is quite daunting. Even their documentation doesn't match their own implementation! Lightspark has improved quite heavily over the past years and has support for AVM1, so that's all great news.

**Comment by eiglow** [comment]
Yeah I guess all that testing I've done over the course of the last 10 months or so has just been with a fake project, a fake piece of software that doesn't actually run or function at all. I just made it all up. You got me.

/s

**Comment by GGor1** [comment]
Yeah, it's 10 months wasted that you'll never get back. You made a big deal out of requesting people to report bugs, so you obviously knew that it was garbage. I have exhausted every effort to get this piece of junk to actually work and it does absolutely nothing. Why claim that it can show flash content on websites when you know it can't? The evidence speaks for itself.

**Comment by GGor1** [comment]
huwdp, are you serious? LOL. What's that saying about a bad work man always blames his tools? You actually blame the most commonly used browsers, then go on to say that LightSpark does work on alleged browsers that nobody has ever heard of. What the hell are Pale Male, Waterfox supposed to be?

**Comment by eiglow** [comment]
@dbluelle Please clean this mess up asap

**Comment by dbluelle** [comment]
For the record:
You were right that the last version of lightspark (0.8.4) didn't work on Windows for a lot of swf files, so please try the new release (0.8.4.1) and create proper bug reports for every swf file that doesn't work.
