### ISSUE TITLE
Swords and Sandals 2 - segfault

### ISSUE THREAD

**Issue by eiglow** [lightspark/lightspark#678]
Tested on current master (50a2e9ae42ba723ab4b2dc21a99851b08814d058)
[SWF](https://github.com/lightspark/lightspark/files/6016976/swordsandsandals2.zip)

Segfault happens almost immediately.

[Backtrace](https://github.com/lightspark/lightspark/files/6016989/bt.log)

I have one debuginfo package missing that I was unable to install, but hopefully it doesn't affect the quality of the backtrace too much.

**Comment by Geo25rey** [comment]
Looks like there's an attempt to assign to net.flash.NetConnection.call which is a method that is already defined. I'm still investigating why this attempt is made, but the reason for the crash is that instead of sending the ReferenceError (generated by the unauthorized assignment) to the flash VM to handle, the thrown error goes uncaught crashing the process. 

I've tested simply ignoring this error and things get further the initial loading screen for the game runs, but gets stuck due to MovieClip.messageBrodcast is unimplemented.

**Comment by Geo25rey** [comment]
Update regarding messageBroadcast:

I found [this comment](https://github.com/ruffle-rs/ruffle/issues/2301#issuecomment-767262868) originally posted by @Herschel in an issue regarding the ruffle project.

So, it seems that MovieClip.messageBroadcast isn't the issue.
