### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by Twilight774** [lightspark/lightspark#859]
#### What operating system are you are running on?

- [ ] Windows 7, 8 or 10
- [ ] Windows XP, Vista or older
- [x] Linux: *Debian 11*
- [ ] Mac OS X: *<specify version here, such as 10.8.1>*
- [ ] Other: *<specify OS and version here>*

```
[ 94%] Building CXX object src/CMakeFiles/spark.dir/3rdparty/avmplus/pcre/pcre_study.cpp.o
/home/user/lightspark/src/3rdparty/avmplus/pcre/pcre_study.cpp: In function ‘int set_start_bits(const uschar*, uschar*, BOOL, BOOL, compile_data*)’:
/home/user/lightspark/src/3rdparty/avmplus/pcre/pcre_study.cpp:426:35: warning: ‘<<’ in boolean context, did you mean ‘<’? [-Wint-in-bool-context]
  426 |             if ((tcode[c/8] && (1 << (c&7))) != 0)
      |                                ~~~^~~~~~~~~

```

**Comment by huwdp** [comment]
Just to let you know, the line here comes from Adobe's source code [here](https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/pcre/pcre_study.cpp#L426).

**Comment by ichfly** [comment]
I think this should be
`if ((tcode[c/8] & (1 << (c&7))) != 0)`
but I dont think that change the behavior in any way because the lsb are ignored by the next line so as long as
tcode[c/8] is checked everything is working. The current code that only checks tcode[c/8] so is faster.
or we could use something like this
```
for (c = 128; c < 256; c+=8)
{
if (tcode[c/8])
```
